/**
 * Point d'entrée unique pour toutes les icônes de l'application.
 * Voir la même logique dans le projet "eleve-pages" — set Feather
 * (react-icons/fi) en priorité, complété par Heroicons 2 (hi2) pour les
 * quelques icônes absentes de Feather.
 */
import {
  FiMusic as Music,
  FiGrid as LayoutDashboard,
  FiBookOpen as BookOpen,
  FiUsers as Users,
  FiMessageCircle as MessageCircle,
  FiSliders as Sliders,
  FiStar as Star,
  FiChevronRight as ChevronRight,
  FiChevronLeft as ChevronLeft,
  FiTrendingUp as TrendingUp,
  FiEdit3 as PenSquare,
  FiTrash2 as Trash2,
  FiVideo as Video,
  FiFileText as FileText,
  FiHeadphones as Headphones,
  FiCheckCircle as CheckCircle2,
  FiXCircle as XCircle,
  FiPlus as Plus,
  FiSearch as Search,
  FiUserX as UserX,
  FiUserCheck as UserCheck,
  FiBarChart2 as BarChart3,
  FiSend as Send,
  FiMenu as Menu,
  FiX as X,
} from "react-icons/fi";
import {
  HiOutlineClipboardDocumentCheck as ClipboardCheck,
  HiOutlineWallet as Wallet,
  HiOutlineShieldCheck as ShieldCheck,
  HiOutlineAcademicCap as GraduationCap,
} from "react-icons/hi2";

export {
  Music,
  LayoutDashboard,
  BookOpen,
  Users,
  MessageCircle,
  Sliders,
  Star,
  ChevronRight,
  ChevronLeft,
  TrendingUp,
  PenSquare,
  Trash2,
  Video,
  FileText,
  Headphones,
  CheckCircle2,
  XCircle,
  Plus,
  Search,
  UserX,
  UserCheck,
  BarChart3,
  Send,
  Menu,
  X,
  ClipboardCheck,
  Wallet,
  ShieldCheck,
  GraduationCap,
};
